import { IBikeItem } from '@/models/Bike';

export const INITIAL_BIKES_SEED: Partial<IBikeItem>[] = [
  {
    title: 'Royal Enfield Hunter 350 Dapper Ash',
    slug: 'royal-enfield-hunter-350-dapper-ash-2023',
    brand: 'Royal Enfield',
    model: 'Hunter 350',
    variant: 'Dapper Ash Dual Channel ABS',
    year: 2023,
    price: 148000,
    fuelType: 'Petrol',
    transmission: 'Manual',
    kilometers: 7200,
    bikeType: 'Street / Naked',
    engineCC: 349,
    mileage: 36,
    color: 'Dapper Ash Silver & Black',
    ownership: '1st Owner',
    location: 'Mumbai (BKC Showroom)',
    description:
      'Impeccably maintained single-owner Royal Enfield Hunter 350 in distinct Dapper Ash livery. Features black alloy wheels, dual-channel ABS, smooth J-Series counterbalanced engine, and a low seat height ideal for urban agility and weekend highway cruising. Full OEM authorized service history logged.',
    features: [
      'Dual-Channel ABS',
      'J-Series 349cc Counterbalanced Engine',
      'Factory Black Cast Alloy Wheels',
      'Digi-Analog Instrument Cluster',
      'USB Type-A Charging Port',
      'Rotary Switchgear Knobs',
      'Tubeless Ceat Zoom XL Tyres',
    ],
    images: [
      '/images/bikes/hunter_350_isolated.png',
      '/images/bikes/hunter_350_hero.jpg',
    ],
    featured: true,
    status: 'Available',
    inspectionScore: 120,
    registrationState: 'MH-02',
    specs: {
      engineCc: 349,
      mileageKmpl: 36,
      powerBhp: 20.2,
      torqueNm: 27.0,
      fuelTankCapacityLiters: 13,
      kerbWeightKg: 181,
      seatHeightMm: 790,
      brakingSystem: 'Dual Channel ABS (300mm Front / 270mm Rear Disc)',
      coolingSystem: 'Air-Oil Cooled',
    },
  },
  {
    title: 'Royal Enfield Classic 350 Stealth Black',
    slug: 'royal-enfield-classic-350-stealth-black-2022',
    brand: 'Royal Enfield',
    model: 'Classic 350',
    variant: 'Stealth Black Dark Edition',
    year: 2022,
    price: 178000,
    fuelType: 'Petrol',
    transmission: 'Manual',
    kilometers: 11400,
    bikeType: 'Cruiser',
    engineCC: 349,
    mileage: 35,
    color: 'Stealth Black Matte',
    ownership: '1st Owner',
    location: 'Bengaluru (Indiranagar)',
    description:
      'Iconic Modern Classic 350 presented in premium factory matte Stealth Black. Equipped with blacked-out mechanicals, dual-disc ABS, ergonomic touring saddle, and signature thump without harsh vibration. Fully tested frame alignment and immaculate cylinder compression.',
    features: [
      'Dual-Channel ABS',
      'Twin Downtube Spine Frame',
      'Low Vibration J-Series Engine',
      'Electronic Fuel Injection (EFI)',
      'Digital LCD Fuel & Trip Display',
      'Touring Crash Guard Installed',
    ],
    images: [
      '/images/bikes/classic_350_isolated.png',
      '/images/bikes/classic_350.jpg',
    ],
    featured: true,
    status: 'Available',
    inspectionScore: 119,
    registrationState: 'KA-01',
    specs: {
      engineCc: 349,
      mileageKmpl: 35,
      powerBhp: 20.2,
      torqueNm: 27.0,
      fuelTankCapacityLiters: 13,
      kerbWeightKg: 195,
      seatHeightMm: 805,
      brakingSystem: 'Dual Channel ABS',
      coolingSystem: 'Air-Oil Cooled',
    },
  },
  {
    title: 'KTM 390 Duke Electronic Orange',
    slug: 'ktm-390-duke-electronic-orange-2023',
    brand: 'KTM',
    model: '390 Duke',
    variant: 'Cornering ABS Quickshifter+',
    year: 2023,
    price: 245000,
    fuelType: 'Petrol',
    transmission: 'Manual',
    kilometers: 6400,
    bikeType: 'Street / Naked',
    engineCC: 373.2,
    mileage: 29,
    color: 'Electronic Orange & Dark Galvanic',
    ownership: '1st Owner',
    location: 'Pune (Koregaon Park)',
    description:
      'The ultimate corner rocket. Equipped with 373cc liquid-cooled single, lightweight split trellis frame, WP APEX inverted forks, cornering ABS with Supermoto mode, and bi-directional Quickshifter+. Pristine condition with complete service records.',
    features: [
      'Cornering ABS with Supermoto Mode',
      'WP APEX 43mm Inverted Forks',
      'Lightweight Split Trellis Frame',
      'Bi-Directional Quickshifter+',
      'Full-Color 5-inch TFT Display',
      'Ride-by-Wire Throttle with Slipper Clutch',
    ],
    images: [
      '/images/bikes/ktm_duke_390_isolated.png',
      '/images/bikes/ktm_duke_390.jpg',
    ],
    featured: true,
    status: 'Available',
    inspectionScore: 120,
    registrationState: 'MH-12',
    specs: {
      engineCc: 373.2,
      mileageKmpl: 29,
      powerBhp: 43.5,
      torqueNm: 37.0,
      fuelTankCapacityLiters: 13.5,
      kerbWeightKg: 167,
      seatHeightMm: 820,
      brakingSystem: 'ByBre 4-Piston Radial 320mm / 230mm Discs',
      coolingSystem: 'Liquid Cooled',
    },
  },
  {
    title: 'Yamaha FZ-S FI V4 Matte Navy',
    slug: 'yamaha-fzs-fi-v4-matte-navy-2023',
    brand: 'Yamaha',
    model: 'FZ-S FI',
    variant: 'Version 4.0 Deluxe',
    year: 2023,
    price: 98000,
    fuelType: 'Petrol',
    transmission: 'Manual',
    kilometers: 6100,
    bikeType: 'Commuter',
    engineCC: 149,
    mileage: 45,
    color: 'Matte Navy Blue with Gold Alloys',
    ownership: '1st Owner',
    location: 'Mumbai (BKC Showroom)',
    description:
      'Yamaha refined Blue Core engine engineering delivering smooth daily commuting and muscular street fighter presence. Equipped with Traction Control System (TCS), Bluetooth Y-Connect telematics, LED flashers, and golden alloy rims.',
    features: [
      'Traction Control System (TCS)',
      'Single-Channel ABS with Disc Brakes',
      'Class-D Bi-Functional LED Headlamp',
      'Yamaha Y-Connect Bluetooth Telematics',
      'Two-Level Single Seat',
      '140/60-17 Radial Rear Tyre',
    ],
    images: [
      '/images/bikes/yamaha_fzs_isolated.png',
      '/images/bikes/yamaha_fzs.jpg',
    ],
    featured: false,
    status: 'Available',
    inspectionScore: 120,
    registrationState: 'MH-03',
    specs: {
      engineCc: 149,
      mileageKmpl: 45,
      powerBhp: 12.4,
      torqueNm: 13.3,
      fuelTankCapacityLiters: 13,
      kerbWeightKg: 136,
      seatHeightMm: 790,
      brakingSystem: 'Front ABS Disc / Rear Disc',
      coolingSystem: 'Air Cooled',
    },
  },
  {
    title: 'TVS Raider 125 Fiery Yellow',
    slug: 'tvs-raider-125-fiery-yellow-2023',
    brand: 'TVS',
    model: 'Raider 125',
    variant: 'Split Seat Disc',
    year: 2023,
    price: 76000,
    fuelType: 'Petrol',
    transmission: 'Manual',
    kilometers: 5300,
    bikeType: 'Commuter',
    engineCC: 124.8,
    mileage: 57,
    color: 'Fiery Yellow & Black',
    ownership: '1st Owner',
    location: 'Delhi NCR (Gurugram)',
    description:
      'Ultra-efficient and sporty 125cc commuter motorcycle featuring distinct animalistic LED headlight DRLs, reverse LCD instrument display, Eco/Power riding modes, and under-seat storage compartment. Exceptional mileage and low maintenance history.',
    features: [
      '3-Valve 125cc Engine with Oil Cooler',
      'Eco and Power Riding Modes',
      'Multi-Color Reverse LCD Display',
      'Synchronized Braking Technology (SBT)',
      'Under-Seat Storage with USB Port',
      'Gas-Charged 5-Step Adjustable Monoshock',
    ],
    images: [
      '/images/bikes/tvs_raider_isolated.png',
      '/images/bikes/tvs_raider.jpg',
    ],
    featured: false,
    status: 'Available',
    inspectionScore: 119,
    registrationState: 'DL-04',
    specs: {
      engineCc: 124.8,
      mileageKmpl: 57,
      powerBhp: 11.38,
      torqueNm: 11.2,
      fuelTankCapacityLiters: 10,
      kerbWeightKg: 123,
      seatHeightMm: 780,
      brakingSystem: 'Front 240mm Disc / Rear 130mm Drum with SBT',
      coolingSystem: 'Air & Oil Cooled',
    },
  },
];
