export interface ISeedCar {
  title: string;
  slug: string;
  brand: string;
  model: string;
  variant: string;
  year: number;
  price: number; // in INR
  fuelType: 'Petrol' | 'Diesel' | 'Electric' | 'Hybrid' | 'CNG';
  transmission: 'Automatic' | 'Manual';
  kilometers: number;
  bodyType: 'SUV' | 'Sedan' | 'Hatchback' | 'Crossover' | 'Coupe';
  color: string;
  ownership: string;
  location: string;
  description: string;
  features: string[];
  images: string[];
  media360?: {
    enabled: boolean;
    frames?: string[];
    frameCount?: number;
  };
  engineSpecs?: {
    displacementCc?: number;
    powerHp?: number;
    torqueNm?: number;
  };
  featured: boolean;
  status: 'Available' | 'Sold' | 'Reserved';
  inspectionScore: number;
  registrationState?: string;
}

export const DEMO_CARS: ISeedCar[] = [
  {
    title: 'Mahindra XUV700 AX7 Luxury',
    slug: 'mahindra-xuv700-ax7-luxury-2023',
    brand: 'Mahindra',
    model: 'XUV700',
    variant: 'AX7 Luxury Pack AWD',
    year: 2023,
    price: 2150000,
    fuelType: 'Diesel',
    transmission: 'Automatic',
    kilometers: 28400,
    bodyType: 'SUV',
    color: 'Midnight Black Metallic',
    ownership: '1st Owner',
    location: 'South Delhi, Delhi NCR',
    description:
      'Immaculately maintained single-owner Mahindra XUV700 in top-tier AX7 Luxury trim with All-Wheel Drive. Complete authorized Mahindra service history with zero structural or flood damage. Features dual 10.25-inch curved digital displays, Sony 3D 12-speaker immersive sound, Level 2 ADAS suite, and panoramic skyroof.',
    features: [
      'Level 2 ADAS (Adaptive Cruise, Lane Keep, AEB)',
      'Sony 3D 12-Speaker Sound with Subwoofer',
      'Panoramic Skyroof',
      'Dual 10.25-inch Integrated HD Screens',
      'Ventilated Front Seats with Electric Memory',
      '360° Surround View Camera with Blind View Monitor',
      'Wireless Apple CarPlay & Android Auto',
      'All-Wheel Drive (AWD) with Drive Modes',
    ],
    images: [
      '/images/inventory/xuv700_hero.jpg',
      '/images/inventory/xuv700_side_view_1790316496815.jpg',
      '/images/inventory/xuv700_rear_quarter_1790316523939.jpg',
      '/images/inventory/xuv700_interior.jpg',
      '/images/inventory/xuv700_front_left_1790316611130.jpg',
    ],
    media360: {
      enabled: true,
      frames: [
        '/images/360/frame_0.jpg',
        '/images/360/frame_1.jpg',
        '/images/360/frame_2.jpg',
        '/images/360/frame_3.jpg',
        '/images/360/frame_4.jpg',
        '/images/360/frame_5.jpg',
        '/images/360/frame_6.jpg',
        '/images/360/frame_7.jpg',
      ],
      frameCount: 8,
    },
    engineSpecs: {
      displacementCc: 2184,
      powerHp: 182,
      torqueNm: 450,
    },
    featured: true,
    status: 'Available',
    inspectionScore: 160,
    registrationState: 'DL (Delhi)',
  },
  {
    title: 'Hyundai Creta SX(O) Knight Edition',
    slug: 'hyundai-creta-sxo-knight-2023',
    brand: 'Hyundai',
    model: 'Creta',
    variant: 'SX(O) Knight Edition IVT',
    year: 2023,
    price: 1720000,
    fuelType: 'Petrol',
    transmission: 'Automatic',
    kilometers: 21800,
    bodyType: 'SUV',
    color: 'Abyss Black with Red Accents',
    ownership: '1st Owner',
    location: 'Bandra West, Mumbai',
    description:
      'Stunning Knight Edition Creta finished in deep Abyss Black with red exterior front brake calipers and bespoke dark chrome grille. Flawlessly serviced with comprehensive digital logs. Equipped with ventilated front seats, panoramic glass roof, Bose premium sound system, and electronic parking brake with auto-hold.',
    features: [
      'Bose 8-Speaker Premium Sound System',
      'Panoramic Electric Sunroof',
      'Front Ventilated Seats',
      'Trio-Beam LED Headlamps & Horizon Lightbar',
      '10.25-inch Touchscreen Navigation',
      'BlueLink Connected Car Tech (60+ Features)',
      'Air Purifier with AQI Display',
      'Wireless Smartphone Charger',
    ],
    images: [
      '/images/inventory/creta_front.jpg',
      '/images/inventory/creta_front_quarter_1790317861358.jpg',
      '/images/inventory/car_interior_cockpit_1790317987200.jpg',
    ],
    media360: { enabled: false },
    engineSpecs: {
      displacementCc: 1497,
      powerHp: 113,
      torqueNm: 144,
    },
    featured: true,
    status: 'Available',
    inspectionScore: 158,
    registrationState: 'MH (Maharashtra)',
  },
  {
    title: 'Kia Seltos GTX Plus Turbo',
    slug: 'kia-seltos-gtx-plus-turbo-2023',
    brand: 'Kia',
    model: 'Seltos',
    variant: 'GTX+ 1.5 T-GDi 7DCT',
    year: 2023,
    price: 1890000,
    fuelType: 'Petrol',
    transmission: 'Automatic',
    kilometers: 16500,
    bodyType: 'SUV',
    color: 'Pewter Olive Matte',
    ownership: '1st Owner',
    location: 'Indiranagar, Bengaluru',
    description:
      'Aureus Certified 2023 Kia Seltos GTX+ boasting the powerful 160 HP 1.5L Turbo petrol engine and lightning-fast 7-speed dual clutch transmission. Exclusive Pewter Olive finish with zero paint touch-ups. Dual 10.25-inch curved display cockpit, Level 2 ADAS safety, heads-up display, and 360-degree camera.',
    features: [
      '1.5L Turbo Petrol (160 HP) with 7-Speed DCT',
      'Level 2 ADAS Safety Suite (17 Autonomous Features)',
      'Dual 10.25-inch Curved Panoramic Displays',
      '8-inch Smart Heads-Up Display (HUD)',
      'Bose 8-Speaker Surround Sound',
      'Smart Pure Air Purifier with Fragrance Cartridge',
      'Dual-Zone Automatic Climate Control',
      '18-inch Crystal Cut Alloy Wheels',
    ],
    images: [
      '/images/inventory/seltos_blue.jpg',
      '/images/inventory/kia_seltos_suv_1790317962615.jpg',
      '/images/inventory/car_interior_cockpit_1790317987200.jpg',
    ],
    media360: { enabled: false },
    engineSpecs: {
      displacementCc: 1482,
      powerHp: 158,
      torqueNm: 253,
    },
    featured: true,
    status: 'Available',
    inspectionScore: 159,
    registrationState: 'KA (Karnataka)',
  },
  {
    title: 'Tata Nexon Fearless Plus DCA',
    slug: 'tata-nexon-fearless-plus-dca-2024',
    brand: 'Tata',
    model: 'Nexon',
    variant: 'Fearless+ S 1.2 Turbo DCA',
    year: 2024,
    price: 1440000,
    fuelType: 'Petrol',
    transmission: 'Automatic',
    kilometers: 9200,
    bodyType: 'SUV',
    color: 'Daytona Grey with Piano Black Roof',
    ownership: '1st Owner',
    location: 'Jubilee Hills, Hyderabad',
    description:
      'Near-new 2024 Tata Nexon in flagship Fearless+ S trim with the cutting-edge Dual Clutch Automatic (DCA) with paddle shifters. 5-Star Global NCAP safety pedigree. Features bi-functional sequential LED headlamps, 10.25-inch high-definition floating infotainment with wireless CarPlay, and 360-degree 3D surround camera.',
    features: [
      '5-Star Global NCAP Adult & Child Safety Rating',
      '7-Speed Dual Clutch Automatic with Paddle Shifters',
      '10.25-inch Slim-Bezel Infotainment by Harman',
      'Full Digital Customizable Instrument Cluster',
      'JBL 9-Speaker Audio with Subwoofer',
      'Front Ventilated Seats',
      '360° High-Definition Surround View System',
      'Sequential LED DRLs & Welcome Animation',
    ],
    images: [
      '/images/inventory/tata_nexon_suv_1790317904989.jpg',
      '/images/inventory/nexon_rear.jpg',
      '/images/inventory/car_interior_cockpit_1790317987200.jpg',
    ],
    media360: { enabled: false },
    engineSpecs: {
      displacementCc: 1199,
      powerHp: 118,
      torqueNm: 170,
    },
    featured: false,
    status: 'Available',
    inspectionScore: 160,
    registrationState: 'TS (Telangana)',
  },
  {
    title: 'Honda City ZX CVT',
    slug: 'honda-city-zx-cvt-2023',
    brand: 'Honda',
    model: 'City',
    variant: 'ZX 1.5 i-VTEC CVT',
    year: 2023,
    price: 1480000,
    fuelType: 'Petrol',
    transmission: 'Automatic',
    kilometers: 24100,
    bodyType: 'Sedan',
    color: 'Platinum White Pearl',
    ownership: '1st Owner',
    location: 'South Delhi, Delhi NCR',
    description:
      'The benchmark executive sedan in India. 5th Generation Honda City ZX with refined 1.5L i-VTEC engine and seamless CVT with 7-speed paddle shifters. Equipped with Honda Sensing ADAS, full LED 9-array jewel headlamps, LaneWatch blindspot camera, and plush dual-tone leatherette upholstery.',
    features: [
      'Honda Sensing ADAS (Collision Mitigation, Adaptive Cruise)',
      'Full LED 9-Array Jewel Headlamps & Z-Shaped 3D Taillamps',
      'Electric Sunroof with One-Touch Auto Open',
      'Honda LaneWatch Blind Spot Camera',
      '8-inch Touchscreen with Wireless Android Auto & CarPlay',
      'Walk-Away Auto Lock & Engine Remote Start',
      'Premium Dual-Tone Leather Upholstery',
      'Paddle Shifters for Manual Control',
    ],
    images: [
      '/images/inventory/honda_city_sedan_1790317886201.jpg',
      '/images/inventory/city_sedan.jpg',
      '/images/inventory/honda_city_interior.jpg',
    ],
    media360: { enabled: false },
    engineSpecs: {
      displacementCc: 1498,
      powerHp: 119,
      torqueNm: 145,
    },
    featured: false,
    status: 'Available',
    inspectionScore: 160,
    registrationState: 'DL (Delhi)',
  },
  {
    title: 'Maruti Grand Vitara Alpha+ Hybrid',
    slug: 'maruti-grand-vitara-alpha-hybrid-2023',
    brand: 'Maruti Suzuki',
    model: 'Grand Vitara',
    variant: 'Alpha+ Intelligent Electric Hybrid e-CVT',
    year: 2023,
    price: 1850000,
    fuelType: 'Hybrid',
    transmission: 'Automatic',
    kilometers: 19800,
    bodyType: 'SUV',
    color: 'Arctic White with Black Roof',
    ownership: '1st Owner',
    location: 'Sector 54, Gurgaon',
    description:
      'State-of-the-art Strong Hybrid SUV offering an astonishing 27.97 km/l ARAI fuel efficiency. Silent EV mode drive in city traffic with seamless battery-engine transitions. Features panoramic sliding sunroof, heads-up display, 360-degree view camera, ventilated front seats, and Qi wireless charging pad.',
    features: [
      'Intelligent Strong Hybrid (EV Mode Capability)',
      'Class-Leading 27.97 km/l Fuel Economy',
      'Panoramic Sliding Glass Sunroof',
      'Heads-Up Display (HUD) with Hybrid Telemetry',
      '360° View Camera with Dynamic Guidelines',
      'Ventilated Front Seats in Rich Bordeaux Faux Leather',
      '9-inch SmartPlay Pro+ Touchscreen with Arkamys Audio',
      'Auto-Dimming Rearview Mirror',
    ],
    images: [
      '/images/inventory/grand_vitara.jpg',
      '/images/inventory/grand_vitara_suv_1790317933233.jpg',
      '/images/inventory/car_interior_cockpit_1790317987200.jpg',
    ],
    media360: { enabled: false },
    engineSpecs: {
      displacementCc: 1490,
      powerHp: 114,
      torqueNm: 141,
    },
    featured: true,
    status: 'Available',
    inspectionScore: 157,
    registrationState: 'HR (Haryana)',
  },
  {
    title: 'Toyota Urban Cruiser Hyryder V Hybrid',
    slug: 'toyota-urban-cruiser-hyryder-v-hybrid-2023',
    brand: 'Toyota',
    model: 'Urban Cruiser Hyryder',
    variant: 'V Strong Hybrid e-CVT',
    year: 2023,
    price: 1940000,
    fuelType: 'Hybrid',
    transmission: 'Automatic',
    kilometers: 14200,
    bodyType: 'SUV',
    color: 'Speedy Blue Metallic',
    ownership: '1st Owner',
    location: 'Koregaon Park, Pune',
    description:
      'Legendary Toyota hybrid engineering in flagship V trim. Striking Speedy Blue with contrasting gloss black roof. Features electric EV drive mode, panoramic sunroof, full digital instrument display, ventilated seats, and Toyota i-Connect suite. 8-year hybrid battery warranty intact.',
    features: [
      'Toyota Self-Charging Hybrid Electric Powertrain',
      'Speedy Blue Metallic Dual-Tone Exterior',
      'Panoramic Double-Slide Sunroof',
      'Ventilated Black & Brown Leatherette Seats',
      'Heads-Up Display & 7-inch TFT Instrument Screen',
      '360° Panoramic View Camera',
      '9-inch Touchscreen with Wireless Smartphone Mirroring',
      '6 Airbags & Electronic Stability Control',
    ],
    images: [
      '/images/inventory/hyryder_blue.jpg',
      '/images/inventory/toyota_hyryder_side.jpg',
      '/images/inventory/indian_suv_showroom_1790315806541.jpg',
    ],
    media360: { enabled: false },
    engineSpecs: {
      displacementCc: 1490,
      powerHp: 114,
      torqueNm: 141,
    },
    featured: false,
    status: 'Available',
    inspectionScore: 160,
    registrationState: 'MH (Maharashtra)',
  },
  {
    title: 'Hyundai Verna SX(O) Turbo DCT',
    slug: 'hyundai-verna-sxo-turbo-dct-2023',
    brand: 'Hyundai',
    model: 'Verna',
    variant: 'SX(O) 1.5 Turbo GDi 7DCT',
    year: 2023,
    price: 1640000,
    fuelType: 'Petrol',
    transmission: 'Automatic',
    kilometers: 18100,
    bodyType: 'Sedan',
    color: 'Titan Grey Metallic',
    ownership: '1st Owner',
    location: 'Alwarpet, Chennai',
    description:
      'Futuristic performance sedan delivering 160 HP and 253 Nm of torque with 0-100 km/h in 8.1 seconds. Horizon LED lightbar with parametric front grille and black 16-inch alloy wheels. Equipped with Level 2 ADAS, heated and ventilated front seats, Bose 8-speaker audio, and 64-color ambient light.',
    features: [
      '1.5L Turbo GDi (160 HP / 253 Nm) - Fastest in Segment',
      'Level 2 ADAS (Forward Collision Avoidance, Blind Spot)',
      'Heated AND Ventilated Front Seats',
      'Horizon LED Front Lightbar & Connected LED Taillamps',
      'Bose Premium 8-Speaker Audio System',
      'Dual 10.25-inch Integrated Displays with Switchable Controls',
      'Electric Sunroof & Smart Trunk Hands-Free Release',
      'Electronic Parking Brake with Auto Hold',
    ],
    images: [
      '/images/inventory/verna_sedan.jpg',
      '/images/inventory/hyundai_verna_rear.jpg',
      '/images/inventory/car_interior_cockpit_1790317987200.jpg',
    ],
    media360: { enabled: false },
    engineSpecs: {
      displacementCc: 1482,
      powerHp: 158,
      torqueNm: 253,
    },
    featured: false,
    status: 'Available',
    inspectionScore: 159,
    registrationState: 'TN (Tamil Nadu)',
  },
  {
    title: 'Skoda Kushaq Monte Carlo 1.5 TSI',
    slug: 'skoda-kushaq-monte-carlo-15-tsi-2023',
    brand: 'Skoda',
    model: 'Kushaq',
    variant: 'Monte Carlo 1.5 TSI DSG',
    year: 2023,
    price: 1780000,
    fuelType: 'Petrol',
    transmission: 'Automatic',
    kilometers: 22300,
    bodyType: 'SUV',
    color: 'Tornado Red with Black Styling',
    ownership: '1st Owner',
    location: 'South Delhi, Delhi NCR',
    description:
      'European driving dynamics at their finest. Exclusive Monte Carlo edition in Tornado Red with blacked-out badging, 17-inch Vega dual-tone alloys with red brake calipers, and bespoke red interior theme. Powered by the acclaimed 1.5L TSI EVO engine with Active Cylinder Technology and 7-speed DSG.',
    features: [
      '1.5L TSI EVO Turbo Engine (150 HP / 250 Nm)',
      '7-Speed DSG Dual Clutch Automatic with Paddle Shifters',
      'Active Cylinder Technology (ACT) for High Fuel Efficiency',
      'Monte Carlo Red-Black Contrast Sports Seats',
      '8-inch Skoda Virtual Cockpit Instrument Cluster',
      '10-inch Touchscreen with Wireless SmartLink',
      'Skoda 6-Speaker Sound System with Subwoofer in Spare Wheel',
      '5-Star Global NCAP Safety Rating',
    ],
    images: [
      '/images/inventory/kushaq_red.jpg',
      '/images/inventory/skoda_kushaq_rear.jpg',
      '/images/inventory/car_interior_cockpit_1790317987200.jpg',
    ],
    media360: { enabled: false },
    engineSpecs: {
      displacementCc: 1498,
      powerHp: 148,
      torqueNm: 250,
    },
    featured: true,
    status: 'Available',
    inspectionScore: 160,
    registrationState: 'DL (Delhi)',
  },
  {
    title: 'Volkswagen Taigun GT Plus 1.5 DSG',
    slug: 'volkswagen-taigun-gt-plus-15-dsg-2023',
    brand: 'Volkswagen',
    model: 'Taigun',
    variant: 'GT Plus 1.5 TSI DSG',
    year: 2023,
    price: 1760000,
    fuelType: 'Petrol',
    transmission: 'Automatic',
    kilometers: 25800,
    bodyType: 'SUV',
    color: 'Curcuma Yellow Metallic',
    ownership: '1st Owner',
    location: 'Sector 50, Noida',
    description:
      'Enthusiast-grade compact SUV engineered on the robust MQB-A0-IN platform with 5-star crash safety. Striking Curcuma Yellow with chrome wing front grille and Infinity LED tail lamps. Features digital cockpit, ventilated front seats, electric sunroof, and red ambient cockpit glow.',
    features: [
      '1.5L TSI Turbocharged Petrol with 7-Speed DSG',
      '5-Star Global NCAP Crash Safety Certified',
      'Infinity Connected LED Tail Lamps with 3D Structure',
      '8-inch Digital Cockpit Instrument Display',
      'Ventilated Leatherette Front Seats',
      '10.1-inch Play Touchscreen with Wireless App-Connect',
      'Electronic Stability Control (ESC) with 40+ Active Sensors',
      'Red Painted Front Brake Calipers & GT Badging',
    ],
    images: [
      '/images/inventory/taigun_yellow.jpg',
      '/images/inventory/vw_taigun_rear.jpg',
      '/images/inventory/car_interior_cockpit_1790317987200.jpg',
    ],
    media360: { enabled: false },
    engineSpecs: {
      displacementCc: 1498,
      powerHp: 148,
      torqueNm: 250,
    },
    featured: false,
    status: 'Available',
    inspectionScore: 158,
    registrationState: 'UP (Uttar Pradesh)',
  },
];
